---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rules
  namespace: applications-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /green
            pathType: Prefix
            backend:
              service:
                name: svc-green
                port:
                  number: 80
          - path: /yellow
            pathType: Prefix
            backend:
              service:
                name: svc-yellow
                port:
                  number: 80
