apiVersion: v1
data:
  auth: Zm9vOiRhcHIxJHlhNFp1WG1SJHFsUUxNOXQ0eDF5aEdPY2NLTW13YjEK
kind: Secret
metadata:
  name: basic-auth
  namespace: applications-namespace
type: Opaque

#the value in data.auth and the secret are created by:

# 1 create the auth file

#$ htpasswd -c auth <username>
#$New password: 
#$Re-type new password: 
#Adding password for user <username>

# 2 create the secret

#$ kubectl create secret generic basic-auth --from-file=auth
