---
apiVersion: v1
kind: Service
metadata:
  name: ingress
  namespace: ingress-namespace
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30001
  selector:
    name: nginx-ingress
  type: NodePort
